<?php
$matriz2 = array
(
    array(
    "França",
    "A culinária da França compreende uma grande variedade de pratos e de grande prestígio no mundo, principalmente no ocidente. A grande variedade de queijos, vinhos, carnes e doces é a imagem de marca da França em termos de gastronomia.
Tradicionalmente, cada região francesa tem uma culinária própria: a culinária do noroeste usa manteiga, crème fraîche e maçãs;  a culinária provençal (do sudeste) prefere azeite, verduras e tomates;  a do sudoeste usa gordura de pato, fígado (foie gras), cogumelos (cèpes) e moelas; a culinária do nordeste relembra a culinária da Alemanha e usa banha de porco, salsichas e chucrute.

Além destas quatro áreas gerais, há muitas mais tipos de culinária locais, como a do vale do Rio Loire, famosa pelos delicados pratos de peixe de água doce e pelos vinhos brancos; a cozinha basca, famosa pelo uso de tomate e pimentão, e a culinária do Roussillon, semelhante à culinária da Catalunha. ",
    ),
    
    array(
    "Itália",
    "A culinária italiana evoluiu através dos séculos, ao longo das mais variadas alterações sociais e políticas; suas raízes podem ser traçadas até o século IV a.C. Mudanças significantes ocorreram com a descoberta do Novo Mundo, que ajudaram a moldar muito do que é conhecido como a culinária italiana hoje em dia, através da introdução de ingredientes como batatas, tomates, pimentões e milho, todos eles parte central da cozinha daquele país, e que no entanto só foram introduzidos em grande escala a partir do século XVIII.",
    ),
    
    array(
    "Alemanha",
    "A culinária da Alemanha varia de região para região. As regiões do sul da Alemanha por exemplo, compartilham uma cultura culinária com a Suíça e com a Áustria. A carne de porco, bovina e de aves são as principais variedades de carne consumida na Alemanha, sendo a carne de porco a mais popular. Em todas as regiões, a carne é muitas vezes comida em forma de salsicha. Mais de 1500 tipos de salsicha são produzidos na Alemanha. Alimentos orgânicos ganharam uma quota de mercado de cerca de 3,0%, e deverão aumentar ainda mais. Um ditado popular alemão tem o significado: 'Tomo o café-da-manhã como um imperador, almoço como um rei e janto como um mendigo'. O café-da-manhã é geralmente uma seleção de pães e baguetes com geleia e mel ou carnes frias e queijo, por vezes acompanhado de um ovo cozido. Cereais ou granola com leite ou iogurte é menos comum, mas generalizado. Mais de 300 tipos de pão são vendidos em lojas de panificação em todo o país.",
    ),


);

?>