<?php 
 $matriz_noticias = array
    (
        array(
            "França",
            "Kouign-Amann: o croissant divino",
            "A classica receita francesa de Kouign Amann possui origem franco-basca e é marcante por reunir uma massa folhada em uma absurda quantidade de camadas junto ao bom e velho açucar, criando um delicioso e macio croissant caramelizado por inteiro. A pronuncia desse nome basco se assemelha a 'Queen-a-mahn'.",
            "https://www.youtube.com/embed/RK7AAI6Zicw"),
        array(
            "França",
            "Coq au Vin: tão antigo quanto Roma",
            "Coq au Vin é provavelmente uma das mais antigas e classicas receitas europeias, primordialmente feita com um galo inteiro cozido no vinho. Atualmente a receita se identifica como frango(normalmente sobrecoxa) cozidas lentamente em um vinho tinto. A tradução literal de Coq au Vin é 'Galo ao Vinho'. ",
            "https://www.youtube.com/embed/2QuVUjCyWbU"),
        array(
            "França",
            "Cassoulet: a receita mais complexamente simples que existe",
            "Apesar da receita do cassoulet se resumir em um cozido de feijão com carne em forno lento, existem diversas variações da receita, de origem Occitâna. Na França existem versões pré feitas enlatadas, mas, quem em sã consciência gostaria de comer um classico desses vindo de uma lata? A receita do vídeo é a versão de cassoulet vinda da cidade de Toulouse",
            "https://www.youtube.com/embed/uOL-IgFC61c"),
        array(
            "Italia",
            "Gelato alla Crema",
            "O Gelato, também conhecido como sorvete italiano é um sorvete a base de leite e creme, conhecido pelo baixo teor de ar na mistura o que leva a uma massa densa e saborosa, de sabor intenso, muito apreciado ao redor do mundo.",
            "https://www.youtube.com/embed/ZQWxEf5z67w"), 
        array(
            "Italia",
            "Spaghetti alla Carbonara: O classico das massas",
            "Carbonara ou spaghetti alla carbonara é uma receita tradicional italiana de massa. O seu nome é derivado da palavra italiana carbone, que significa carvão.Acredita-se que tenha sido uma receita apreciada pelos preparadores de carvão vegetal dos montes apeninos, na região italiana da Úmbria.
            A receita original de Roma é preparada com ovos, queijo parmesão, queijo pecorino romano, guanciale, pimenta preta e banha, azeite ou manteiga. ",
            "https://img.ibxk.com.br///2018/09/06/06164716963170-t1200x480.jpg"),
        array(
            "Hardware",
            "Nova impressora 3D da HP faz objetos de metal em escala industrial",
            "A HP movimentou o setor de impressão 3D com o anúncio de um novo modelo. Trata-se da Metal Jet, que como o nome já entrega é um dispositivo capaz de criar modelos em três dimensões totalmente de metal, em vez dos tradicionais materiais derivados do plástico. Segundo a fabricante, a Metal Jet tem um método de impressão 50 vezes mais eficiente que os já existentes, é mais veloz e traz um custo mais baixo comparado com outros sistemas de jateamento.",
            "https://img.ibxk.com.br//2018/09/10/10114525136032-t1200x480.jpg"), 
        array(
            "Mercado",
            "Ministério da Cultura vai investir R$ 100 mi em política pública para games",
            "Durante a Game XP, o ministro da Cultura, Sérgio Sá Leitão, revelou que o MinC vai criar uma política pública para o setor de games que terá um investimento de R$ 100 milhões – que serão distribuídos entre linhas estratégicas de desenvolvimento de jogos, desenvolvimento e produção de conteúdo em VR e AR, lançamento de novos títulos, aceleração de empresas do segmento, investimentos em mostras e festivais, infraestrutura e tecnologia, além de formação e capacitação.",
            "https://img.ibxk.com.br//2018/09/11/11082313062008-t1200x480.jpg"), 
        array(
            "Hardware",
            "Para competição mais acirrada, Intel confirma Adaptative Sync em GPU",
            "O futuro do mercado de placas de vídeo tem aumentado a expectativa a cada anúncio. A NVIDIA tem em suas placas a tecnologia Ray Tracing, nas GPUs de microarquitetura Turing; AMD, por outro lado, não teve anúncios de nenhuma tecnologia gráfica, porém promete trazer as primeiras GPU de 7 nm, o que pode significar aprimoramentos de energia e performance; a Intel, somente por ter anunciado a sua chegada com sistema gráfico dedicado, já garante surpresas.",
            "https://img.ibxk.com.br///2018/09/01/01233103985046-t1200x480.jpg"),         
        array(
            "Mercado",
            "Como as ‘novas tecnologias’ estão impactando o mundo?",
            "O futuro do mundo é o mais conectado possível. E não estamos falando apenas das simples vantagens de comunicação que a internet nos oferece através de nosso PC ou celular: como está ficando bastante claro mesmo hoje, várias tecnologias que antes pareceriam saídas de um filme de ficção científica estão, nos últimos anos, tomando o mercado, como o caso da inteligência artificial, do Blockchain ou mesmo do Big Data.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg")
    ); 
?>